In [1]:
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
dataFrame = pd.DataFrame(pd.read_csv("/Users/gaurwik/Documents/Science_Fair_2023/calenviroscreen-3.0-results-june-2018-update.csv"))
numeric_only = dataFrame._get_numeric_data()
numeric_only

,Census Tract,Total Population,ZIP,Longitude,Latitude,CES 3.0 Score,CES 3.0 Percentile,Ozone,Ozone Pctl,PM2.5,...,Linguistic Isolation Pctl,Poverty,Poverty Pctl,Unemployment,Unemployment Pctl,Housing Burden,Housing Burden Pctl,Pop. Char.,Pop. Char. Score,Pop. Char. Pctl
0,6019001100,3174,93706,-119.781696,36.709695,94.09,100.00,0.065,98.18,15.400000,...,77.51,76.3,97.12,17.6,91.72,26.0,79.40,92.12,9.55,99.70
1,6071001600,6133,91761,-117.618013,34.057780,90.68,99.99,0.062,91.10,13.310000,...,96.25,72.5,94.63,12.3,71.82,34.1,93.75,87.44,9.07,98.11
2,6019000200,3167,93706,-119.805504,36.735491,85.97,99.97,0.062,91.10,15.400000,...,78.39,86.8,99.56,16.1,87.98,40.1,97.85,94.58,9.81,99.99
3,6077000801,6692,95203,-121.314524,37.940517,82.49,99.96,0.046,53.02,12.540000,...,75.14,61.3,85.57,19.6,94.97,21.1,63.54,86.70,8.99,97.72
4,6019001500,2206,93725,-119.717843,36.681600,82.03,99.95,0.065,98.18,15.400000,...,73.72,66.4,90.23,18.6,93.65,28.1,83.98,80.08,8.30,92.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8030,6009000504,942,95223,-120.211151,38.405130,NaN,NaN,0.055,77.87,4.645934,...,NaN,24.7,35.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8031,6065940100,166,92239,-114.475335,34.000183,NaN,NaN,0.044,40.49,9.945784,...,NaN,21.0,28.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8032,6053011502,1710,93923,-121.735102,36.301079,NaN,NaN,0.035,16.94,3.991772,...,10.76,29.0,43.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8033,6083980100,11,57,-120.048221,33.948186,NaN,NaN,0.040,25.87,9.536303,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8034,6111980000,56,61,-119.503588,33.255655,NaN,NaN,0.042,31.84,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
def isExcluded(row):
    excludedWords = {"Score", "Pctl", "CES 3.0", "Pop. Char.", "Longitude", "Latitude", "Housing Burden", "Pollution Burden"}
    for i in excludedWords:
        if (i in row[0][0] or i in row[0][1]):
            return False
    
    return row[0][0] != row[0][1]

In [5]:
corr = dataFrame.corr()
c1 = corr.abs().unstack()
c1 = c1.drop_duplicates()
c1 = c1.sort_values(ascending=False)

oldDf = pd.DataFrame(c1)
df = pd.Series
first = True
for row in oldDf.iterrows():
    if (isExcluded(row)):
        x = pd.Series([row[0][0], row[0][1], row[1]])
        if (first):
            df = x
            first = False
        else:
            df = pd.concat([df, x], axis = 1, ignore_index=True)

df = pd.DataFrame(df)
df = df.transpose()
display(df)

,0,1,2
0,Education,Poverty,"0 0.819775 Name: (Education, Poverty), dtyp..."
1,Education,Linguistic Isolation,"0 0.736859 Name: (Education, Linguistic Iso..."
2,Asthma,Cardiovascular Disease,"0 0.663415 Name: (Asthma, Cardiovascular Di..."
3,Linguistic Isolation,Poverty,"0 0.616986 Name: (Linguistic Isolation, Pov..."
4,Poverty,Unemployment,"0 0.597475 Name: (Poverty, Unemployment), d..."
...,...,...,...
226,Total Population,Asthma,"0 0.002285 Name: (Total Population, Asthma)..."
227,Traffic,Solid Waste,"0 0.001538 Name: (Traffic, Solid Waste), dt..."
228,Total Population,Low Birth Weight,"0 0.001339 Name: (Total Population, Low Bir..."
229,Total Population,Poverty,"0 0.001189 Name: (Total Population, Poverty..."
230,Pesticides,Haz. Waste,"0 0.00038 Name: (Pesticides, Haz. Waste), d..."

In [6]:
health = {"Asthma", "Low Birth Weight", "Cardiovascular Disease"}
healthDf = pd.Series
first = True
for row in df.iterrows():
    if (row[1][0] in health or row[1][1] in health):
        x = pd.Series([row[0], row[1][0], row[1][1], row[1][2]])
        if (first):
            healthDf = x
            first = False
        else:
            healthDf = pd.concat([healthDf, x], axis = 1, ignore_index = True)

healthDf = pd.DataFrame(healthDf)
healthDf = healthDf.transpose()
display(healthDf)

,0,1,2,3
0,2,Asthma,Cardiovascular Disease,"0 0.663415 Name: (Asthma, Cardiovascular Di..."
1,6,Asthma,Poverty,"0 0.487867 Name: (Asthma, Poverty), dtype: ..."
2,9,Cardiovascular Disease,Unemployment,"0 0.419873 Name: (Cardiovascular Disease, U..."
3,10,Asthma,Unemployment,"0 0.419843 Name: (Asthma, Unemployment), dt..."
4,11,Cardiovascular Disease,Poverty,"0 0.415957 Name: (Cardiovascular Disease, P..."
5,14,Ozone,Cardiovascular Disease,"0 0.398129 Name: (Ozone, Cardiovascular Dis..."
6,15,Asthma,Education,"0 0.392243 Name: (Asthma, Education), dtype..."
7,16,Cardiovascular Disease,Education,"0 0.379663 Name: (Cardiovascular Disease, E..."
8,20,Asthma,Low Birth Weight,"0 0.346124 Name: (Asthma, Low Birth Weight)..."
9,21,Low Birth Weight,Poverty,"0 0.324179 Name: (Low Birth Weight, Poverty..."
10,26,Low Birth Weight,Education,"0 0.288228 Name: (Low Birth Weight, Educati..."
11,27,Low Birth Weight,Unemployment,"0 0.273446 Name: (Low Birth Weight, Unemplo..."
12,30,Low Birth Weight,Cardiovascular Disease,"0 0.234776 Name: (Low Birth Weight, Cardiov..."
13,37,Low Birth Weight,Linguistic Isolation,"0 0.210949 Name: (Low Birth Weight, Linguis..."
14,42,Census Tract,Asthma,"0 0.192927 Name: (Census Tract, Asthma), dt..."
15,44,Diesel PM,Asthma,"0 0.185347 Name: (Diesel PM, Asthma), dtype..."
16,46,Drinking Water,Cardiovascular Disease,"0 0.18403 Name: (Drinking Water, Cardiovasc..."
17,47,Asthma,Linguistic Isolation,"0 0.182748 Name: (Asthma, Linguistic Isolat..."
18,51,PM2.5,Low Birth Weight,"0 0.175175 Name: (PM2.5, Low Birth Weight),..."
19,57,Diesel PM,Low Birth Weight,"0 0.164683 Name: (Diesel PM, Low Birth Weig..."
20,67,PM2.5,Cardiovascular Disease,"0 0.14831 Name: (PM2.5, Cardiovascular Dise..."
21,72,Cleanup Sites,Asthma,"0 0.128302 Name: (Cleanup Sites, Asthma), d..."
22,79,Census Tract,Low Birth Weight,"0 0.120162 Name: (Census Tract, Low Birth W..."
23,80,Groundwater Threats,Asthma,"0 0.118162 Name: (Groundwater Threats, Asth..."
24,85,Cardiovascular Disease,Linguistic Isolation,"0 0.11267 Name: (Cardiovascular Disease, Li..."
25,93,Total Population,Cardiovascular Disease,"0 0.104096 Name: (Total Population, Cardiov..."
26,96,Imp. Water Bodies,Cardiovascular Disease,"0 0.099234 Name: (Imp. Water Bodies, Cardio..."
27,97,Ozone,Low Birth Weight,"0 0.098236 Name: (Ozone, Low Birth Weight),..."
28,101,PM2.5,Asthma,"0 0.093264 Name: (PM2.5, Asthma), dtype: fl..."
29,107,Haz. Waste,Asthma,"0 0.087784 Name: (Haz. Waste, Asthma), dtyp..."
30,108,Cleanup Sites,Low Birth Weight,"0 0.086485 Name: (Cleanup Sites, Low Birth ..."
31,111,ZIP,Low Birth Weight,"0 0.082412 Name: (ZIP, Low Birth Weight), d..."
32,122,Traffic,Low Birth Weight,"0 0.07336 Name: (Traffic, Low Birth Weight)..."
33,125,ZIP,Asthma,"0 0.07203 Name: (ZIP, Asthma), dtype: float64"
34,133,Ozone,Asthma,"0 0.065048 Name: (Ozone, Asthma), dtype: fl..."
35,135,Traffic,Cardiovascular Disease,"0 0.064221 Name: (Traffic, Cardiovascular D..."
36,136,Census Tract,Cardiovascular Disease,"0 0.063654 Name: (Census Tract, Cardiovascu..."
37,142,Drinking Water,Low Birth Weight,"0 0.058315 Name: (Drinking Water, Low Birth..."
38,143,Solid Waste,Asthma,"0 0.057625 Name: (Solid Waste, Asthma), dty..."
39,146,Drinking Water,Asthma,"0 0.055355 Name: (Drinking Water, Asthma), ..."
40,151,Solid Waste,Cardiovascular Disease,"0 0.051316 Name: (Solid Waste, Cardiovascul..."
41,155,Haz. Waste,Low Birth Weight,"0 0.04745 Name: (Haz. Waste, Low Birth Weig..."
42,161,Imp. Water Bodies,Low Birth Weight,"0 0.04136 Name: (Imp. Water Bodies, Low Bir..."
43,165,Tox. Release,Asthma,"0 0.039193 Name: (Tox. Release, Asthma), dt..."
44,169,ZIP,Cardiovascular Disease,"0 0.034806 Name: (ZIP, Cardiovascular Disea..."
45,171,Solid Waste,Low Birth Weight,"0 0.034268 Name: (Solid Waste, Low Birth We..."
46,178,Diesel PM,Cardiovascular Disease,"0 0.029067 Name: (Diesel PM, Cardiovascular..."
47,181,Groundwater Threats,Low Birth Weight,"0 0.027906 Name: (Groundwater Threats, Low ..."
48,192,Traffic,Asthma,"0 0.023562 Name: (Traffic, Asthma), dtype: ..."
49,196,Imp. Water Bodies,Asthma,"0 0.021602 Name: (Imp. Water Bodies, Asthma..."
50,197,Pesticides,Low Birth Weight,"0 0.020736 Name: (Pesticides, Low Birth Wei..."
51,199,Haz. Waste,Cardiovascular Disease,"0 0.019712 Name: (Haz. Waste, Cardiovascula..."
52,202,Cleanup Sites,Cardiovascular Disease,"0 0.017355 Name: (Cleanup Sites, Cardiovasc..."
53,205,Tox. Release,Low Birth Weight,"0 0.015382 Name: (Tox. Release, Low Birth W..."
54,208,Tox. Release,Cardiovascular Disease,"0 0.013309 Name: (Tox. Release, Cardiovascu..."
55,211,Groundwater Threats,Cardiovascular Disease,"0 0.010958 Name: (Groundwater Threats, Card..."
56,217,Pesticides,Cardiovascular Disease,"0 0.008432 Name: (Pesticides, Cardiovascula..."
57,223,Pesticides,Asthma,"0 0.004315 Name: (Pesticides, Asthma), dtyp..."
58,226,Total Population,Asthma,"0 0.002285 Name: (Total Population, Asthma)..."
59,228,Total Population,Low Birth Weight,"0 0.001339 Name: (Total Population, Low Bir..."

In [7]:
pollution = {"Ozone", "PM2.5", "Diesel PM", "Drinking Water", "Pesticides", "Tox. Release", "Traffic", 
"Cleanup Sites", "Groundwater Threats", "Haz. Waste", "Imp. Water Bodies", "Solid Waste"}

polDf = pd.Series
first = True
for row in df.iterrows():
    if (row[1][0] in pollution or row[1][1] in pollution):
        x = pd.Series([row[0], row[1][0], row[1][1], row[1][2]])
        if (first):
            polDf = x
            first = False
        else:
            polDf = pd.concat([polDf, x], axis = 1, ignore_index = True)

polDf = pd.DataFrame(polDf)
polDf = polDf.transpose()
display(polDf)

,0,1,2,3
0,5,Ozone,Drinking Water,"0 0.556655 Name: (Ozone, Drinking Water), d..."
1,7,Cleanup Sites,Haz. Waste,"0 0.452287 Name: (Cleanup Sites, Haz. Waste..."
2,12,Cleanup Sites,Groundwater Threats,"0 0.409698 Name: (Cleanup Sites, Groundwate..."
3,13,Ozone,PM2.5,"0 0.401895 Name: (Ozone, PM2.5), dtype: flo..."
4,14,Ozone,Cardiovascular Disease,"0 0.398129 Name: (Ozone, Cardiovascular Dis..."
...,...,...,...,...
181,223,Pesticides,Asthma,"0 0.004315 Name: (Pesticides, Asthma), dtyp..."
182,224,Census Tract,Groundwater Threats,"0 0.003269 Name: (Census Tract, Groundwater..."
183,225,ZIP,Cleanup Sites,"0 0.002367 Name: (ZIP, Cleanup Sites), dtyp..."
184,227,Traffic,Solid Waste,"0 0.001538 Name: (Traffic, Solid Waste), dt..."
185,230,Pesticides,Haz. Waste,"0 0.00038 Name: (Pesticides, Haz. Waste), d..."